### ISSUE TITLE
After output is captured to variable, "default" output is no longer set 

### ISSUE THREAD

**Issue by NeilMacMullen** [scriban/scriban#297]
Possibly a misunderstanding on my part but after the "capture" feature has been used it's no longer possible to retrieve the main output from the TemplateContext.Output property...

```
        [TestMethod]
        public void Capture()
        {
            var text = @"outer1{{capture test}}text{{end}}outer2";
            var compiledTemplate = Template.Parse(text);
            var scriptObject1 = new ScriptObject();
            var context = new TemplateContext();
            context.PushGlobal(scriptObject1);

            var result = compiledTemplate.Render(context);
            result.Should().Be("outer1outer2");
            context.Output.ToString().Should().Be("outer1outer2");
        }
```

**Comment by xoofx** [comment]
It has been by design like this from quite some time already:

https://github.com/scriban/scriban/blob/c6c8a108becf67824268cfb1d17599ca70794204/src/Scriban/Template.cs#L181-L191

So if you want to have access to it, you might have to implement your own Render method (which is using behind public methods, so it should be easy to workaround this design issue)

**Comment by NeilMacMullen** [comment]
Ok - no problem if it's deliberate behaviour I will work with it :-)
