### ISSUE TITLE
Scriban does not support variables with a `-` ?

### ISSUE THREAD

**Issue by StefH** [scriban/scriban#304]
Like this:

```
{{request.headers.Content-Type}}
```

Just returns empty string.

**Comment by xoofx** [comment]
No, it does not support it (in fact, it supports it only in Liquid mode, because in Liquid it was allowed)

`-` is supposed to be a binary operator for the substract expression in scriban. I was a bit worried about introducing this also to Scriban (Liquid doesn't that this issue because they don't support binary expressions)

**Comment by StefH** [comment]
Thanks for the explanation.
