### ISSUE TITLE
Retrieve Token List From Template

### ISSUE THREAD

**Issue by ElGregory** [scriban/scriban#325]
I've seen a few tickets come and go regarding retrieving a list of expected tokens from a given template. Each referenced the new visitor pattern as the way it will be done in 3.x but i haven't been able to find any code examples or documentation on the new feature. I was able to find the list of statements assembled after Template.Parse() but nothing more straightforward than that.

Is there now a way to collect the tokens used by a given template? I'd like to save the tokens and a sample model with each template for things like qa testing but I'm still not sure how best to parse out the tokens. Any help or guidance would be greatly appreciated.

PS. Thanks for such a powerful tool. This is about the only thing I haven't figured out how to make work for us yet.

**Comment by xoofx** [comment]
There is no way to get access to the list of tokens easily, you could go through tokens from the syntax tree, but it's probably easier to lex the tokens separately. Something like:

```
// LexerOptions should have same option than the one passed by Template.Parse
var lexer = new Lexer(textToParse, "/path/to/source.txt", new LexerOptions() { ... }); 
var tokens = lexer.ToList();
```

**Comment by ElGregory** [comment]
Ahh, I see. It may not be the "tokens" that I want after all, I may have misspoke. I'm looking for a list of template variables. Is there a way to pull the text out of the token? The Statements collection (template.Page.Body.Statements) seems closer to what I'm looking for than the token list so I'm wondering if I'm not using the right terms. I think I could get the below code to give me what I want if I'm able to parse through it and fish out the variables used but I was hoping the tokens were what I was after.

`
                var template = Template.Parse(selectedSentence.Template);
                var statements = template.Page.Body.Statements;
`

**Comment by xoofx** [comment]
Oh, ok, so definitely not tokens. Looking for template variables can be tricky because you can have access like `this["my_variable"]` that would be more difficult to detect, specially if "my_variable" is not a string but coming from another variable...

But otherwise, you can certainly do that with a ScriptVisitor, you have this method that you can override this method:

https://github.com/scriban/scriban/blob/82c88748b8fc32d35e92c2c1a8911901b5fae90e/src/Scriban/ScribanVisitors.generated.cs#L1439

to look for `ScriptGlobalVariable`. You will have to play with the visitor to not enter functions or to treat them differenrtly. You will have also to disambiguate cases like a `ScriptMemberExpression` like `a.b` both `a` and `b` will be reported as a ScriptGlobalVariable`...etc.

It's perfectly possible, and the visitor and the syntax tree should be enough simple that you will find your way around.

**Comment by ElGregory** [comment]
Super! ScriptGlobalVariable is the term I was lacking. I can't wait to play with this!!

Thanks!!
