### ISSUE TITLE
Lazy Load Values

### ISSUE THREAD

**Issue by Adam-Howarth** [scriban/scriban#366]
We have a similar issue that has been reported in #323. We have created class that lazy load all properties but are running into the same problem that all of the properties are being evaluated despite not being used.

Adding a dummy class as the root object and referencing all properties using "model." (the example in #323) isn't really a viable solution for us. We have scoped out the changes for creating a PR that will allow us to keep the models as is through creating a "Lazy" script object. Which would also require changes to the extension method Import so set those values correctly.

But before we go down that route, has this approach been explored before? If so were there any problems that arose? Is there a workaround outside of moving the properties off of the route?

If not we are willing create a PR but wanted to gauge the likelihood of that being accepted. Naturally you would have to see the code first, but reaching out in case there is something we can do beforehand.

**Comment by SRBobGilliland** [comment]
@xoofx Any thoughts?

**Comment by xoofx** [comment]
> @xoofx Any thoughts?

I'm on holidays, I will try comment back in August

**Comment by xoofx** [comment]
You can push your own top level `IScriptObject` to a template context (`TemplateContext.PushGlobal`), as long as it respects the contract, you should be able to implement any lazy loading you want, redirecting to any underlying managed objects or not. You would have also to respect the storing part of the contract (e.g store variable).
I would suggest to implement this on your side first, you can share the code here if you want. But not sure I would like to maintain such a scenario. I'm worried it can be very use case specific, some would start to come with other requirements (e.g I want to bind multiple properties from different objects on the top level script but with lazy...etc.)...
Anyway, you should not be blocked to implement such feature on top of Scriban without forking Scriban. Let me know.

**Comment by ShiroMiyuki** [comment]
Hi, I tried implementing it on my end it worked somehow ok, but there is an issue with importing the object, as we can add our 
delegates to try to change the value we retrieved in the object, but we also need to wrap the values into lazy objects / or Func's and that logic is sitting inside the ScriptObjectExtensions:::Import method.

I forked the solution and the easiest way to go around it was indeed not to implement lazy loading inside the existing solution to satisfy our needs but to add the delegates and expose them in the import method.

I ran the tests and all of them passed as well as I ran the performance checks. The difference in code before and after code change seems to not impact the overall performance too much (it's -3 to 3 us less/more so I think it's within margin error)

I raised PR for the change
https://github.com/scriban/scriban/pull/376

**Comment by ShiroMiyuki** [comment]
If this potentially could be accepted I'll be happy to add more changes to PR if needed like few lines in documentation etc

**Comment by xoofx** [comment]
Thanks @ShiroMiyuki. I had a look at your PR but I will have to decline it: I don't think it is a proper way to solve this issue. As I explained above, implementing a derived class from `IScriptObject` is more appropriate to support this kind of scenarios, as you can decide from the derived class what to lazy load, or how to proxy to another .NET object.

**Comment by ShiroMiyuki** [comment]
I had to implement class delivering from IScriptObject, but it was not enough, as it was accessing all the properties when we import the object via the Import method. 
All the properties on the object are not marked as lazy (so string/DateTime/object/ etc), but they are loaded only when accessed. 
Scriban by loading the value of the property triggers lazy loading. 
Implementing the IScript object as is solves only part of the problem - the resolving of the values when they are accessed. 
However, when we import the object it still accesses all the fields. That renders the whole import method unusable in our case, to make it work we either needed to write our own custom import method or copy-paste your import method and replace 2 lines 

```
property.GetValue(obj)
field.GetValue(obj)
```
with 
```
new Lazy<object>(() => property.GetValue(obj))
new Lazy<object>(() => field.GetValue(obj))
```

so to the issue is to make it possible for scriban to actually lazy load the values rather than just unpack Lazy properties and get value so we don't need to append each property with `.value` postfix.

The implementation of the Script object looks like 

```
private class LazyScriptObject : ScriptObject
	{
		public void LazyImport(object model, MemberFilterDelegate filter = null, MemberRenamerDelegate renamer = null)
		{
			this.Import(model,
				renamer: member => member.Name,
				fieldSetter: new FieldValueSetterDelegate((info, obj) => new LazyLoadedValue(() => info.GetValue(obj))),
				propertySetter: new PropertyValueSetterDelegate((info, obj) => new LazyLoadedValue(() => info.GetValue(obj))));
		}
		public override bool TryGetValue(TemplateContext context, SourceSpan span, string member, out object value)
		{
			var getValue = base.TryGetValue(context, span, member, out value);
			if (!getValue)
			{
				return false;
			}
			// unpack lazy value
			if (value is LazyLoadedValue)
			{
				LazyLoadedValue lazyValue = (LazyLoadedValue)value;
				value = lazyValue.GetValue();
			}
			return true;
		}
		private struct LazyLoadedValue
		{
			private Lazy<object> _lazyValue;
			public LazyLoadedValue(Func<object> valueFactory)
			{
				this._lazyValue = new Lazy<object>(valueFactory);
			}
			public object GetValue()
			{
				return _lazyValue.Value;
			}
		}
	}
```

I couldn't see the other way around than either implementing our custom import method or, like mentioned earlier, copy-pasting your import method and wrap the 'GetValue' methods with lazy loading. 
Obviously, both approaches are not perfect, implementing by ourselves will probably not support all the edge cases scriban is supporting, and copy-pasting is also not perfect, because we will need to change the import method each time you change it in here.

Is there something I'm missing here that would solve the issue of making scriban lazy load the values?

**Comment by xoofx** [comment]
> Is there something I'm missing here that would solve the issue of making scriban lazy load the values?

That's the thing, you should not use Import anymore, it is not appropriate for lazy loading. You need to bind the lazy value in `TryGetValue`. This is where you do the lazy loading (you call the method by reflection in TryGetValue)

For example, there is a [TypeObjectAccessor](https://github.com/scriban/scriban/blob/master/src/Scriban/Runtime/Accessors/TypedObjectAccessor.cs) in Scriban that does exactly lazy loading. What you are looking for is the mix of this + a mix of a regular `ScriptObject` (that could store value)

**Comment by ShiroMiyuki** [comment]
Oh, I think I get it now!

So I should implement a Script object that has the `TypedObjectAccessor` and when we invoke the `TryGetValue` we would pass the arguments to the `TypedObjectAccessor` and return the value we got from there.

Yep, that sounds like it should work! Thanks!
