### ISSUE TITLE
Is available parent/layout page of template?

### ISSUE THREAD

**Issue by tenebraeee** [scriban/scriban#369]
Hi. For example, in Razor we can use layout page. scribian contains similar tool? Or other example, in Nunlucks we can use sections for this goals.

**Comment by AlfredoMS** [comment]
previously discussed topic shows a workaround to make this possible: https://github.com/scriban/scriban/issues/52

**Comment by xoofx** [comment]
Layout concepts are up to the engine embedding Scriban and there should be nothing in Scriban to block you to implement the way you want a layout system to work.
There is little incentive to make this as part of Scriban because there are various way to implement it. For example, I'm using a [YAML based layout system in lunet](https://github.com/lunet-io/lunet/blob/master/src/Lunet.Layouts/LayoutProcessor.cs) where the layout is defined in the YAML frontmatter and processed iteratively.
