### ISSUE TITLE
Default file extension

### ISSUE THREAD

**Issue by edsulaiman** [scriban/scriban#370]
as we know, liquid uses `.liquid` razor uses `.cshtml` or `.razor`.
what is the file extension for scriban? `.scriban`? or `.html`?

**Comment by edsulaiman** [comment]
I found the answer here [Scriban Syntax Coloring extension for Visual Studio Code
](https://marketplace.visualstudio.com/items?itemName=xoofx.scriban)

**Comment by binarycow** [comment]
Note, that Scriban itself does not require any specific file extension. The
file extensions you found apply to the vs code plugin - the extension has
to have a file extension in order to know when to activate Scriban
highlighting

That being said, in my own applications, I use the same extensions as the
vs code plugin - `scriban` for code only templates, and `sbn-txt` for mixed
templates.
