### ISSUE TITLE
Does this support serializing the interpreter?

### ISSUE THREAD

**Issue by dustinlacewell** [scriban/scriban#389]

**Comment by xoofx** [comment]
Could you clarify? Serializing the AST you mean? (e.g an interpreter interprets the AST)
What is the use case?
Serialization today can be done through Scriban by text

**Comment by dustinlacewell** [comment]
Serializing the actual interpreter VM to disk, to pause it, and resume execution at a later time.

**Comment by xoofx** [comment]
No, there is nothing like that and probably impossible to bring it. It would require to rewrite entirely the way the interpreter is working so that its state can be restored (while today, it relies on the stack and regular function calls). The whole `TemplateContext` would have to be restored, which could be a challenge as well (global variables and contexts, outputs...etc.)

**Comment by dustinlacewell** [comment]
I understand, thanks.
