### ISSUE TITLE
Alternative c-like syntax

### ISSUE THREAD

**Issue by lofcz** [scriban/scriban#411]
Since Scriban already has a concept of different parsing modes this proposes a new mode `Clike` to accompany `Scientific`.
In this mode syntax differs from default implementation.

## Syntax changes
_aligned to https://github.com/scriban/scriban/blob/master/doc/language.md_

2. Comments
```cs
# -> //
## -> /* */
```
_nested comments are not allowed for brevity_

7. Functions
```cs
{{func sub
   ret $0 - $1
end}}

->

{{func sub {
   ret $0 - $1
} }}

```
```cs
{{func add(a, b)
   ret a + b
end}}

->

{{func add(a, b) {
   ret a + b
} }}

```

9.3 if <expression>, else, else if <expression>
```cs
{{
if <expression>
  ...
else if <expression>
  ...
else 
  ...
end
}}

->

{{
if (?<expression>)? {
  ...
}
else if (?<expression>)? {
 
}
else {
  ...
}
}}
```

9.4 case and when
```cs
{{

    x = 5
    case x
      when 1, 2, 3
          "Value is 1 or 2 or 3
      when 5
          "Value is 5"
      else
          "Value is " + x
    end

    ->

    x = 5
    case(?x)? {
      when 1, 2, 3 {?
          "Value is 1 or 2 or 3
      }?
      when 5 {?
          "Value is 5"
      }?
      else {?
          "Value is " + x
      }?
}}
```

9.5 Loops
```cs
{{for <variable> in <expression>}} 
  ... 
{{end}}

->

{{for (?<variable> in <expression>)? { 
  ... 
 } }}
```

```cs
{{while <expression>}}

{{ end }}

-> 

{{while (?<expression>)? { 

 } }}
```

9.6 Capture 

```cs
{{ capture myvariable }}

{{ end }}

->

{{ capture (?myvariable)? { 

 } }}
```

9.9 With 

```cs
myobject = {}
with myobject
  member1 = "yes"
end

->

myobject = {}
with (?myobject)? {
  member1 = "yes"
}
```

This boils down to:
1. Blocks are defined using `{}` instead of `statement.. end`.
2. Allow parentheses around some of the keywords.
3. Auto transfer to text blocks from control / loop statements.

```cs
{{
for (?<variable> in <expression>)? { 
  <div>{{ for.index }}</div>
} 
}}
```

4. Alternative notation for comments, possibly `#` can be kept as well.

## Rationale
Scriban offers great sandboxing and is therefore a good fit for environments where such constraints are necessary. Some c# developers would prefer familiar clike syntax of Razor to code templates in but due to said need for sandboxing and/or other features unique to Scriban and thus native Razor cannot be used. 

Proposed changes would also render Scriban fitter for writing "backend" scripts _(templates with no text blocks)_ in as current syntax is hard to look at when working with deeply nested control/loop statements.

**Comment by lofcz** [comment]
I currently don't have much time to work on this but I would love to sponsor implementation of this feature.

**Comment by xoofx** [comment]
Hello, thanks for the description. I understand the rationale but unfortunately, I will have to decline.

The different syntax modes are still keeping most of the core of the syntax, but what you would like to introduce a syntax that is actually a different language. 

Not sure also that it is practical. For example:

```
{{while (?<expression>)? { 

 } }}
```

Is not equivalent to 

```
{{while <expression>}}

{{ end }}
```

When you start to have some inline text inside the while (or the capture or anything else)

You would have to write something like this:

```
{{while (?<expression>)? { }}

{{ } }}
```

Because Scriban doesn't have a support for a block statement with start/end markers, these `{` and `}` are not super pleasant to visualize in a text template. You would prefer then to introduce different code start/end marker.

Scriban has a permissive license, so it can be forked and changed more substantially if necessary on your side.

I would also suggest to revisit Razor, as you might be able validate the template with e.g Roslyn (I don't know if they provide such a step) or to hook into it to make sure they are using "validated" API, if that's a concern.
