### ISSUE TITLE
Passing / using loop variable inside an inner function

### ISSUE THREAD

**Issue by pebezo** [scriban/scriban#412]
One issue in our upgrade from 1.2.2 to 5.0 that we missed (we have a test case now) is when we have a `for` loop over a collection and inside the `for` loop we call another Scriban function that uses the loop variable. For example:

```
{{ for o in offers }} {{ snippet }} = {{ o.something }} | {{ end }} 
```

while the `snippet` function's template looks like this:

```
[ from inside the snippet {{ o.something }} ]
```

In this example, outputting `o.something` directly inside the loop works fine. It outputs the value of `something` in the `o` variable. However, if we try to use `o.something` from the `snippet` function we get:

```
<input>(1,32) : error : Cannot get the member o.something for a null object.
```

It looks like (guessing) the `o` value doesn't automatically bubble down to the `snippet` function. This exact same code worked in 1.2.2, but doesn't work in 5.0. Here's a runnable repro:

https://github.com/pebezo/ScribanRepro

Is there a way to re-enable the 1.2.2 functionality in 5.0?

Thanks

**Comment by xoofx** [comment]
> It looks like (guessing) the o value doesn't automatically bubble down to the snippet function. This exact same code worked in 1.2.2, but doesn't work in 5.0. Here's a runnable repro:

Yes, the behavior changed because I went through some errors in some templates that were leaking variables and I was seeing this as design problem, but yeah, I see also that you were relying on this feature.

> Is there a way to re-enable the 1.2.2 functionality in 5.0?

The only thing I can see is to introduce a new property on e.g `TemplateContext.EnableLoopVariableAsGlobal` that would revert to the previous behavior.

**Comment by xoofx** [comment]
> Yes, the behavior changed because I went through some errors in some templates that were leaking variables and I was seeing this as a design problem, but yeah, I see also that you were relying on this feature.

For example. If you have a for loop in one function, and you call another function that is using the same variable, you could quickly start to have weird behavior where you don't understand why the outer variable is different.

But maybe I can workaround it by making the variable readonly somehow.

Also because of that design, a variable set by a loop was leaking outside of the loop (as the "last value"). Is it something that you were also relying on?

**Comment by pebezo** [comment]
> Yes, the behavior changed because I went through some errors in some templates that were leaking variables and I was seeing this as a design problem, but yeah, I see also that you were relying on this feature.

Yes, it makes perfect sense to have this behavior as the default; it's safer. Unfortunately we've used this behavior in many places (too many to be feasible to update by hand).

> But maybe I can workaround it by making the variable readonly somehow.

That'd be perfectly fine/reasonable. We're not changing the values in the loop, just reading them.

> Also because of that design, a variable set by a loop was leaking outside of the loop (as the "last value"). Is it something that you were also relying on?

No... and if we are that'd definitely be a "bug" (unintended behavior)  on our end and we'd fix that by hand.

> The only thing I can see is to introduce a new property on e.g TemplateContext.EnableLoopVariableAsGlobal that would revert to the previous behavior.

That'd be awesome... or if there's another way for us to `push` those variables from code that'd work as well. Maybe modifying the `snippet` function to teach it to use the loop variables? All our functions are already low level by using `IScriptCustomFunction`...

**Comment by xoofx** [comment]
So I had a look, and what I said was incorrect. You can access loop variables in nested functions, but in your repo, you are recreating a new RenderContext [here](https://github.com/pebezo/ScribanRepro/blob/1d902fc9e94a43b1eb457ea37e6ed1ac003c956a/ScribanRepro/RenderRepository.cs#L28) when you render the sub function, and in that case that cannot work, because you are basically discarding previous loop variables. Loop variables are no longer part of the global variable object. You have to use the same TemplateContext when you render nested functions.
