### ISSUE TITLE
[Question] Use as a scripting language?

### ISSUE THREAD

**Issue by jods4** [scriban/scriban#416]
Can I use Scriban as a scripting engine to drive some logic _outside_ a template?
I would like to invoke scriban functions (provided as text) and get back data instead of formatting a template.

One use case I have in mind right now is that I would like to decide which source input I'm gonna run templates on based on freely scriptable conditions.

The main driver would be C#, which would provide the source set of inputs, then somehow (??) invoke user-written scriban functions and get back data (not a templated strnig), which C# would then run templates on.

**Comment by pebezo** [comment]
We've using the template's Evaluate() function for expression evaluation. Something like `var1 + var2 > my_func`. If the result is a boolean then this works great. For more complex "outputs" you could provide a custom model to your context/functions and check how those were changed by your functions after the "render". I don't know if this is the best way, will let Alexandre chime in, but it does work...

**Comment by xoofx** [comment]
> Can I use Scriban as a scripting engine to drive some logic outside a template?

Yes, [kalk](https://kalk.dev/) is for example a calculator entirely built on Scriban. Originally Scriban was mainly focused on templating, but it has changed since version 4.0+

I forgot to update the front-page readme about it. There is [some doc](https://github.com/scriban/scriban/blob/master/doc/runtime.md#evaluating-an-expression) about evaluating directly an expression as @pebezo suggested.

kalk is not using this method directly but using the similar code behind it that is fully accessible as well. For example, it is separating the parsing from the evaluation to provide more feedback after parsing and before evaluating.

**Comment by jods4** [comment]
Thanks for the tips! Kalk looks intriguing! 👀 

I found the bits about evaluating an expression but only an expression is too limiting and would not cut it for me.

In the end, I used a "master" template to pilot everything. I provide a runtime function to divert output to multiple files, which was easy enough thanks to `PushOutput` / `PopOutput`.
Basically implemented #212 myself. 😆 

It works great, thanks for scriban!
