### ISSUE TITLE
date.parse does not store time zone offset

### ISSUE THREAD

**Issue by Ansssss** [scriban/scriban#431]
https://github.com/scriban/scriban/blob/master/doc/builtins.md#dateparse
The above documentation indicates that the format specified in to_string can be used in the pattern parameter of date.parse. I tried this out, but it seems that the date.parse function does not actually store the offset from UTC in the date object. Instead it uses my local timezone information.

Reproduction code:
```
using Scriban;
Template template = Template.Parse(
    @"{{date.format='%FT%T.%N%Z'}}{{ date.parse '2018~06~17~13~59~+08:00' '%Y~%m~%d~%H~%M~%Z' }}");
var result = template.Render();
Console.WriteLine(result);
//Expected: 2018-06-17T13:59:00.000000000+08:00
//Actual:   2018-06-17T00:59:00.000000000-05:00
```

**Comment by xoofx** [comment]
Yes, it's by design here:

https://github.com/scriban/scriban/blob/34396529f637455bc059d609d18630d1d1b57547/src/Scriban/Functions/DateTimeFunctions.cs#L321

The date functions is only exposing `DateTime` not `DateTimeOffset`. You can add your own function helpers to handle `DateTimeOffset` directly.

**Comment by Ansssss** [comment]
Ah, my misunderstanding then. The underlying value is a DateTime, not a DateTimeOffset.
