### ISSUE TITLE
extend string namespace with custom function?

### ISSUE THREAD

**Issue by jezzsantos** [scriban/scriban#436]
Question?
Is it possible to define a custom function (call it `to_plural`), and add it as a `ScriptObject` to my `TemplateContext` such that it is available in my template like this? 

```
{{model.thing | string.to_plural}} 
```
and still have all the other built-in string functions available? like: `{{ thing | string.downcase}}`

Seems like I cannot get both sets of functions in the `string` namespace.

**Comment by xoofx** [comment]
All builtins objects (e.g `string`) are `ScriptObject` and functions (e.g `downcase`) are regular delegates (almost).

```c#
var stringObject = (ScriptObject)myTemplateContext.BuiltinObject["string"];
stringObject.Import(...); // new function to import
```

You can share builtin functions by passing your own builtin object to the TemplateContext constructor (by default it [creates a default BuiltinsFunction](https://github.com/scriban/scriban/blob/b849c549eed423eb2a3e111b759ae8a256aaee60/src/Scriban/TemplateContext.cs#L903-L911))

You can also inherit from `StringFunctions` and add your new static:

```c#
    public class MyStringFunctions : StringFunctions
    {
         public static string ToPlural(string text) => ...;
    }
```

And then use this instance instead of StringFunctions:

```c#
myTemplateContext.BuiltinObject["string"] = new MyStringFunctions();
```

Then there are plenty of different ways to do it, depending on your use case, but you can manipulate all these objects and functions programmatically (e.g copy them around, remove some functions...etc.). For example, in the Liquid syntax, we are rerouting all Liquid functions to their Scriban equivalent ([here](https://github.com/scriban/scriban/blob/b849c549eed423eb2a3e111b759ae8a256aaee60/src/Scriban/Functions/LiquidBuiltinsFunctions.cs#L99-L160))

**Comment by jezzsantos** [comment]
@xoofx I really could not get this going, using this code:
```
var sourceData = new ScriptObject();
                sourceData.Import(model);

                var context = new TemplateContext();
                context.PushGlobal(sourceData);
                context.BuiltinObject["string"] = new CustomScribanStringFunctions();

                return engine.Render(context);
```
where: 
```
internal class CustomScribanStringFunctions : Scriban.Functions.StringFunctions
    {
        public static string Camelcase(string text)
        {
            return text?.ToCamelCase();
        }

        public static string Pascalcase(string text)
        {
            return text?.ToPascalCase();
        }
```

in this unit test, I get: `<input>(1,15) : error : The function `string.camelcase` was not found`
```
        [Fact]
        public void WhenTransformWithCamelCase_ThenReturnsTransformedTemplate()
        {
            var model = new
            {
                aproperty = "OneTwoThree"
            };

            var result = model.Transform("adescription", "{{aproperty | string.camelcase}}");

            result.Should().Be("oneTwoThree");
        }
```

**Comment by jezzsantos** [comment]
OK, this worked:
```
                var context = new TemplateContext();
                var thing = (ScriptObject)context.BuiltinObject["string"];
                thing.Import(typeof(CustomScribanStringFunctions));
```
where `CustomScribanStringFunctions ` was declared as `internal class CustomScribanStringFunctions : ScriptObject`
