### ISSUE TITLE
Fails when using custom chars (and I presume others as well)

### ISSUE THREAD

**Issue by marinusmaurice** [scriban/scriban#442]
Made this modification to one of the test cases. It will fail on others as well.

  public void TestAssign2()
        {
            Assert.AreEqual("variable", Template.ParseLiquid("{% assign  = 'variable' %}{{a}}").Render());
        }

To fix, read the source as Rune's instead of string as  a start.

Its a fault far too common in programming languages.

**Comment by xoofx** [comment]
Wow, ok, let me put the record straight on your issue.

> Fails when using custom chars (and I presume others as well)

So firstly, If you mean custom chars, characters that have codepoints that require in UTF-16 to have [surrogate pairs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding-introduction#surrogate-pairs), indeed, it's not supported in Scriban for identifiers (but you can use them in strings/raw blocks)

The code in Scriban is here

https://github.com/scriban/scriban/blob/b849c549eed423eb2a3e111b759ae8a256aaee60/src/Scriban/Parsing/Lexer.cs#L1305-L1315

You can see that it is handling partly UTF-16 characters, so still wider than ASCII, but not a full codepoint.

> To fix, read the source as Rune's instead of string as a start.

Secondly, Scriban was developed at a time I didn't care much about this for identifier, so indeed, does not support identifier which requires surrogate. I have written since then several parsers that are taking such cases into account (because it's part of their specs, see e.g TOML handling [here](https://github.com/xoofx/Tomlyn/blob/ff0296f552b8042eabc63fd29108aaddbe17c6ce/src/Tomlyn/Text/StringCharacterIterator.cs#L19-L32))

So I know what is a Rune, if you thought I didn't.

> Its a fault far too common in programming languages.

Lastly, that one is actually quite misleading. Supporting [unicode identifers](https://unicode.org/reports/tr31/) for identifiers in programming language is not a requirement. If I had to redo this in Scriban, I would just support plain ASCII. That's a choice, not some kind of "table of the law".

So, in Scriban, I don't plan to change this, it's by design. Nobody has complained about that for the past 6 years.

Note: the character `` that you selected shows how ridiculous using such characters is, my browser is displaying something that is unreadable. What's the point of writing something like that if it is not just to play with rhetoric?
Also, many modern programming fonts support only a small subset of characters in identifiers, so hold your breath in your crusade, because you gonna have to complain a lot around the world about this topic.

**Comment by marinusmaurice** [comment]
Thank you for your reply, and yes as the inventor of the language you are well entitled to implement it however you see fit.
Its just that I speak and read and write in more than just English and hence like to code in such languages and name things as the language(not the programming one) requires for example, the variable named "earlier" would be "vroeër" in one of my other languages I'm fluent in .. which your language wont be able to handle.

But like I said. You the inventor of it, its then completely up to you how you feel it should be implemented. And btw.. it is a very well done language otherwise
