### ISSUE TITLE
array.join with function argument is broken

### ISSUE THREAD

**Issue by rick-de-water** [scriban/scriban#455]
`array.join` does not work properly when using the function argument. Instead of putting the separator between each transformed value, it add the separators to the end.

**Input**
```
{{ func foo(x) }}({{ x }}){{ end }}
{{ bar = [1, 2, 3, 4, 5] }}
{{ bar | array.join ", " }}
{{ bar | array.join ", " @foo }}
```

**Expected output**
```
1, 2, 3, 4, 5
(1), (2), (3), (4), (5)
```

**Actual output**
```
1, 2, 3, 4, 5
(1)(2)(3)(4)(5), , , , 
```

**Comment by xoofx** [comment]
The output is actually correct. Your foo function is interacting directly with the output stream because it is `outputting `(` and `)` to stdout directly, and so it doesn't return anything. Hence why you have `(1)(2)...` output before `,,,,`.

Your function should be more written like this `{{ func foo(x); ret '(' + x + ')'; end }}` and you will get the correct output.

Using your existing function would require a more convoluted filter function like `array.join ""|"" @(do; capture $x; foo($[0]); end; ret $x; end) }}` to capture the output of the foo function
