### ISSUE TITLE
Issue while using Scriban reference dll in WPF Application (.NET Framework)

### ISSUE THREAD

**Issue by Sadhiq6** [scriban/scriban#462]
Hi I have my code before adding the reference scriban library
![image](https://user-images.githubusercontent.com/106057140/192804424-f6d3bf32-48ac-4331-965b-ab548211bb53.png)
 and after attaching scriban library 
![image](https://user-images.githubusercontent.com/106057140/192804511-fcdeedec-701d-4b43-9126-b0f6d45d000d.png)
with the error listed below 
![image](https://user-images.githubusercontent.com/106057140/192804660-49eaaa44-ce2b-41ac-9ebf-b79b252be4bf.png)
please guide me in this scenario.

**Comment by xoofx** [comment]
I answered already on #461, please don't reopen an issue.
The code that is not working has nothing to do with Scriban, even if you just attach the library and you see this error, the problem is somewhere else.

**Comment by binarycow** [comment]
@Sadhiq6 - I agree with @xoofx , It's probably not Scriban in particular that's causing your issue.

_However_... it is interesting that you have the issue only once Scriban has been referenced.

Here's what I know:


First, your project is targeting .NET Framework (as opposed to .NET Core, or .NET 5 or higher), or at the very least, its using the old-style `.csproj` file.  You can see the difference in the solution view:
![image](https://user-images.githubusercontent.com/37249876/192903566-f9d57b2f-49ca-4e7e-a040-80b5f277a5e1.png)

[At least one other project](https://github.com/dotnet/SqlClient/issues/426#issuecomment-586521243) has had to add the `NeutralResourcesLanguageAttribute` to their library to prevent exactly this issue.  But, it appears Scriban already has this set.
![image](https://user-images.githubusercontent.com/37249876/192907326-2f99b11d-ec8a-4f0e-8662-451ed0585a8f.png)


[Someone](https://stackoverflow.com/questions/72967910/visual-studio-2022-could-not-load-type-system-resources-neutralresourceslangua) has seen this issue because they were referencing the `.dll` directly, instead of referencing a NuGet package


----

**So** - @Sadhiq6 - If you can give me a link to a git repo that reproduces this issue, I don't mind taking a look.  I haven't been able to reproduce it on my machine.

**Comment by xoofx** [comment]
Thanks @binarycow, didn't notice that it was an old .NET FWK project... @Sadhiq6 which version of the Scriban dll did you picked up? Which .NET FWK Version your project is using?

**Comment by Sadhiq6** [comment]
> @Sadhiq6 - I agree with @xoofx , It's probably not Scriban in particular that's causing your issue.
> 
> _However_... it is interesting that you have the issue only once Scriban has been referenced.
> 
> Here's what I know:
> 
> First, your project is targeting .NET Framework (as opposed to .NET Core, or .NET 5 or higher), or at the very least, its using the old-style `.csproj` file. You can see the difference in the solution view: ![image](https://user-images.githubusercontent.com/37249876/192903566-f9d57b2f-49ca-4e7e-a040-80b5f277a5e1.png)
> 
> [At least one other project](https://github.com/dotnet/SqlClient/issues/426#issuecomment-586521243) has had to add the `NeutralResourcesLanguageAttribute` to their library to prevent exactly this issue. But, it appears Scriban already has this set. ![image](https://user-images.githubusercontent.com/37249876/192907326-2f99b11d-ec8a-4f0e-8662-451ed0585a8f.png)
> 
> [Someone](https://stackoverflow.com/questions/72967910/visual-studio-2022-could-not-load-type-system-resources-neutralresourceslangua) has seen this issue because they were referencing the `.dll` directly, instead of referencing a NuGet package
> 
> **So** - @Sadhiq6 - If you can give me a link to a git repo that reproduces this issue, I don't mind taking a look. I haven't been able to reproduce it on my machine.

I have attached the link to my repository can you kindly help me to figure out and solve the error? 
https://github.com/Sadhiq6/WpfApp2

**Comment by Sadhiq6** [comment]
> Thanks @binarycow, didn't notice that it was an old .NET FWK project... @Sadhiq6 which version of the Scriban dll did you picked up? Which .NET FWK Version your project is using?

@xoofx Scriban version 5.5.0 is the latest one used in my project and the .Net framework used in my project 4.5.2

**Comment by xoofx** [comment]
>   .Net framework used in my project 4.5.2

That's likely the problem. Scriban only supports netstandard2.0+, and so it is only supported by `net48`
