### ISSUE TITLE
[Feature] Scriban.SourceGenerator

### ISSUE THREAD

**Issue by workgroupengineering** [scriban/scriban#493]
Add roslyn source generator that generate source code of parsing template.
Workflow:

When adding a project file with a .scriban extension, for example: `Blocks.scriban`. The Scriban.SourceGenerator parses `Books.scriban` and generates static Class Books with the Render method only.

**Comment by xoofx** [comment]
Thanks for the proposal, but I will decline it for the following reasons:

1. Generating source code would not bring almost any benefit in terms of speed (if that's what you are looking for?) because of the many things that are happening behind the scene that still need to happen (calls to `TemplateContext` virtual methods, [code for loops](https://github.com/scriban/scriban/blob/8953646e0c746abc95a5b69d4edc5a4f05ec2ae4/src/Scriban/Syntax/Statements/ScriptForStatement.cs#L99-L229)...etc.).
2. If you are looking for such a solution, I would advise to use Razor instead.
3. I'm not in a position to support such work or to maintain it. But also, I don't have time/incentive to design/develop it.
