### ISSUE TITLE
Question: Can I access context on custom c# function?

### ISSUE THREAD

**Issue by OrgesKreka** [scriban/scriban#536]
Hi there, 
Firstly thank you very much for this wonderful project, I really enjoy using it every time i need to generate email/invoice templates.
Lately I am experimenting on using scriban as template to write dynamic sql queries.
How I am handling this is like.
1. I have a json object that contains configurations for filters:
``` json
{
  "filters": {
  "filterName": [ "filterValue1", "filterValue2" ]
}
}
````

2. When i write the sql template I do something like this:
```sql
select * from foo
where 1 = 1
{{  append_in( filters?.filterName, "filterName"  )  }} ## append_in is a custom function
````
3. This is the AppendIn function in C#
```csharp
    public static string AppendIn(object? values, string filterName, string condition = "AND")
	{

		var inString =  string.Join( ',', object); // Just to show the idea, there is validation and casting to array.
 
		if(string.IsNullOrEmpty( filterName )) throw new ArgumentException( nameof( filterName ) );

		return $" {condition} {filterName} IN ( {inString} )";
	}
````

I want to improve the thing by removing the filterName passed in the C# function, is this possible ? 
Can I now the name of the variable that was passed there ?

Secondly In the configuration json I want to pass a sql dialect type, like sqlServer, postgres etc and later inside the AppendIn function based on the sql dialect I can generate the In statement more specifically, example if it is sqlServer the generated statement would be
`AND filterName IN (   'filterValue1', 'filterValue2' )` while if the dialect is postgres the generated statement would be something like `AND filterName in (   values ( 'filterValue1'),( 'filterValue2' )  ) `
Is it possible to access the context inside the AppendIn function?

Thank you!

**Comment by xoofx** [comment]
> I want to improve the thing by removing the filterName passed in the C# function, is this possible ?
> Can I now the name of the variable that was passed there ?

In the doc [here](https://github.com/scriban/scriban/blob/master/doc/runtime.md#scriptobject-advanced-usages) there is a slight mention of being able to add a `TemplateContext` as a first parameter of your function (that get passed implicitly).

From there, you can access `TemplateContext.CurrentNode` which gives you access to the AST. From there, you can go through the AST to recover e.g `filterName` property.

There is also a support (not documented this one) where you can have a parameter that is a `ScriptExpression` and instead of evaluating the parameter, it will pass the AST without evaluating it. I used this feature in kalk for example [here](https://github.com/xoofx/kalk/blob/80cd768fa0212bd65a07f5aeaf73344cf75404fe/src/Kalk.Core/KalkEngine.Functions.General.cs#L389), where I can pass an expression without e.g escaping with quotes, and parse it as it was a string.

**Comment by OrgesKreka** [comment]
Thank you very much for the response @xoofx, I will start playing with your suggestions to see how I can handle them.
Keep up the good work!
