### ISSUE TITLE
MemberRenamer only works on top level members

### ISSUE THREAD

**Issue by atlemann** [scriban/scriban#548]
I have an F# object defined as:

```fsharp
type DisplayValueDto =
    { Value: string
      DisplayValue: string }
```

and a type that uses it:

```fsharp
type SomeObject =
    { MyValue: DisplayValueDto }
```

and in my template I'd like to be able to copy-paste the members instead of snake_casing everythingj:

```html
<td><label>{{ MyValue.DisplayValue }}</label></td>
```

If I call render like this it seems to work

```fsharp
let someObject = ...

let html = template.Render(someObject, (fun memberInfo -> memberInfo.Name))
```

however if I pass my object into a `ScriptObject` it seems to only work on the top level members:

```fsharp

let someObject = ...

let ctx = TemplateContext()
let scriptObj = ScriptObject()
scriptObj.Import(someObject, null, (fun (memberInfo: MemberInfo) -> memberInfo.Name))
ctx.PushGlobal scriptObj

let html = template.Render(ctx)
```

I have to use snake_case on `display_value` like so:

```html
<td><label>{{ MyValue.display_value }}</label></td>
```

Is that expected?

**Comment by BrianVallelunga** [comment]
I'm having a very similar issue that I have set up like this:

```f#
let dotNetRenamer = fun (m: MemberInfo) -> m.Name

let context = TemplateContext()
let scriptObject = new ScriptObject()
let source = { Contact = {| FirstName = "Bob" |} }
scriptObject.Import(source , renamer = dotNetRenamer)
context.PushGlobal(scriptObject)

let template = Template.Parse("Hello {{Contact.FirstName}}")
template.Render(context) // This renders just "Hello "
```

I'm not sure if this is an F# issue or something else.

**Comment by xoofx** [comment]
> however if I pass my object into a `ScriptObject` it seems to only work on the top level members:

There are two places required to setup the member renamer:

- One where you import an object into a `ScriptObject` and you have to pass it explicitely at import time. This ScriptObject is defined outside a TemplateContext, so we need to specify it at this time
- One where you need to specify it for the whole `TemplateContext` when you access indirect .NET objects through the objects that you put in the initial model passed to `TemplateContext.Render`. In that case, you need to setup the MemberRenamer also on the [TemplateContext.MemberRenamer](https://github.com/scriban/scriban/blob/5343f93bc465c6ff6c36aa6316d880be022eeb6e/src/Scriban/TemplateContext.cs#L279)

Both of this is described in the [MemberRenamer doc here](https://github.com/scriban/scriban/blob/master/doc/runtime.md#member-renamer), so I'm quite surprised that this topic comes again and again. People complain when there are no docs, but when there are docs, folks don't read them. So what can we do to improve this? 

If you feel that the documentation is not clear, please help this project by contributing to the doc.

Thank you ☺️

**Comment by BrianVallelunga** [comment]
Thanks for pointing out the issue. I wasn't entirely sure if it was related to `MemberRenamer`, but just posted here because I was seeing a similar behavior. I read docs, but not that one. Instead I was just stepping through the source as I thought perhaps it was a type registration issue and not a `MemberRenamer` issue. I also tend to assume my issues might be related to using F#.

As for what could be done to improve the visibility of this issue, perhaps creating a thin wrapper around `TemplateContext` that will remove the need for setting the `MemberRenamer`? Or a static method such as `TemplateContext.CreateWithDefaultDotNetConventions()`. I would think most .NET dev would expect this behavior out of the box, even though overriding it, once you know how, is incredibly easy.

Anyway, thanks again.

**Comment by xoofx** [comment]
> I would think most .NET dev would expect this behavior out of the box, even though overriding it, once you know how, is incredibly easy.

Yeah, agreed, this stupid convention that I followed initially to make it familiar for folks coming from liquid has caused a significant amount of issues here and there, recently for example in #572 and #565

If I could redesign this library, I would take the default C# naming convention for sure 😅 

> As for what could be done to improve the visibility of this issue, perhaps creating a thin wrapper around TemplateContext that will remove the need for setting the MemberRenamer? Or a static method such as TemplateContext.CreateWithDefaultDotNetConventions()

Not sure that bringing another extension method or wrapper would solve things though. People would still not use it because otherwise they would be already aware of this particularity about MemberRenamer (It's even in the front line of the readme!). Also, that would not solve the problem of importing an object into a ScriptObject... otherwise I would have to use a global static, and I hate global statics, so yeah, the battle is lost... I think 🙂
