### ISSUE TITLE
How to turn off js warnings on Scriban files in Visual Studio 2022?

### ISSUE THREAD

**Issue by gcaplan** [scriban/scriban#568]
Hi folks

Not an issue with Scriban as such - more a problem with usage in Visual Studio (Community).

VS doesn't have a Scriban extension, so I'm editing the code in VS Code with the .scriban-html file extension.

The files are large and complex. The problem is that when anyone opens one of these files in Visual Studio, the Error List is hammered with literally hundreds of errors. 

I've tried all the usual ways to suppress errors in the .proj file and in the Options - Text Editor menu and VS simply ignores them. I tried associating .scriban-html with the html or the javascript editor with linter turned off, and still no joy. I've also tried placing error suppression  statements directly in the <script /> area of the code. 

Obviously, I've tried relaunch, clean and rebuild to try and get the settings to activate.

Nothing works - it almost feels malevolent! Does anyone know a sure -fire way to achieve this? I can't be the only user who has encountered this issue. 

Any help would be fervently appreciated!

**Comment by xoofx** [comment]
By default, opening a `.sbn-html` file in VS should open the default editor, so you won't have syntax highlighting but at least it will be editable. Otherwise, you have to recommend your users to use VS Code.

I don't have other solutions. It is a limitation of VS, so you might want to send feedback to them directly. 🙂

**Comment by k3davis** [comment]
This issue is (rightly) closed, but I found it when trying to figure out if there was tooling for scriban in vs2022, and then, why not.

I assume it's because the textmate functionality of VS is comparatively rudimentary? I tried wrapping the grammars from the vscode extension in a VS extension and could only get keywords to highlight, not regions like `{{...}}`. It seems it would be a relatively complex undertaking to make a vs extension for scriban, even if it only supported syntax coloring and not intellisense, etc.

This doesn't deserve attention which is why I'm not creating a new issue - I'm just in a position where I have to pass on this scripting language due to lack of tooling support in VS, which is disappointing. I assume there are structural reasons why that is and not just "vscode is cooler."
